id: P009202
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23564
  title: བཀའ་བརྒྱུད་གསེར་འཕྲེང
  author: ''
  volumes:
    3eae4db099cd4f068092275642f92aba:
      image_group_id: I2157
      title: ''
      volume_number: 1
      total_pages: 454
      base_file: v001.txt
